# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  VulkanL_config = debug_x64

else ifeq ($(config),debug_arm64)
  VulkanL_config = debug_arm64

else ifeq ($(config),release_x64)
  VulkanL_config = release_x64

else ifeq ($(config),release_arm64)
  VulkanL_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := VulkanL

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

VulkanL:
ifneq (,$(VulkanL_config))
	@echo "==== Building VulkanL ($(VulkanL_config)) ===="
	@${MAKE} --no-print-directory -C source -f Makefile config=$(VulkanL_config)
endif

clean:
	@${MAKE} --no-print-directory -C source -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   VulkanL"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"